actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than $DELETE_AGE days (default is 45)
      for filebeat and metricbeat prefixed indices.
    options:
      ignore_empty_list: 'True'
      disable_action: 'False'
    filters:
    # - filtertype: pattern
    #   kind: regex
    #   value: "^(filebeat-|metricbeat-).*$"
    # - filtertype: age
    #   source: name
    #   direction: older
    #   timestring: '%Y.%m.%d'
    #   unit: days
    #   unit_count: 4
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 4
