actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 3 days (based on index name), for filebeat-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 3

docker run --rm --network seedbox_hidden miffyliye/curator-cli --host "http://elasticsearch:9200" --dry-run delete_indices --ignore_empty_list --filter_list '[{"filtertype":"pattern","kind":"prefix","value":"filebeat-7.3.2-"},{"filtertype":"age","source":"name","direction":"older","timestring":"%Y.%m.%d","unit":"days","unit_count":3}]'
