version: '3'

services:

  samba:
    container_name: samba
    image: dperson/samba
    domainname: ${DOMAIN_NAME}
    command: '-s "shared;/mount;yes;no;yes;all;none"'
    restart: ${RESTART_MODE}
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./download:/mount/downloads
      - ./work:/mount/work
      - /mnt/games:/mount/games
      - /mnt/media:/mount/media
    networks:
        discovery:
            ipv4_address: 10.0.0.50
    dns:
      - 10.0.0.54
      - 1.1.1.1
    labels:
      - "traefik.enable=false"

  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${PUID}
      TZ: ${TIMEZONE}
    networks:
        discovery:
            ipv4_address: 10.0.0.51
    depends_on:
      - pihole
    dns:
      - 10.0.0.54
      - 1.1.1.1

  traefik:
    container_name: traefik
    domainname: ${DOMAIN_NAME}
    image: traefik
    restart: ${RESTART_MODE}
    # Note I opt to whitelist certain apps for exposure to traefik instead of auto discovery
    # use `--docker.exposedbydefault=true` if you don't want to have to do this
    command: "--api --docker"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/traefik.toml
    networks:
        discovery:
            ipv4_address: 10.0.0.52
    dns:
      - 10.0.0.54
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/traefik"
      - "traefik.backend=traefik"
      - "traefik.port=8080"

  # whoami:
  #   container_name: whoami
  #   image: emilevauge/whoami # A container that exposes an API to show its IP address
  #   domainname: ${DOMAIN_NAME}
  #   restart: ${RESTART_MODE}
  #   networks:
  #       discovery:
  #           ipv4_address: 10.0.0.53
  #   dns:
  #     - 10.0.0.54
  #     - 1.1.1.1
  #   depends_on:
  #     - traefik
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/whoami"

  pihole:
    container_name: pihole
    domainname: ${DOMAIN_NAME}
    cap_add:
      - net_admin
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
    # run `touch ./pihole.log` first unless you like errors
    #  - ./pihole.log:/var/log/pihole.log
      - ./config/pihole:/etc/pihole/
      - ./config/dnsmasqd:/etc/dnsmasq.d/
    environment:
      ServerIP: 10.0.0.54
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${GLOBAL_PASSWORD}
      DNSMASQ_LISTENING: all
      INTERFACE: ${NIC_INTERFACE}
      DNS1: 185.187.240.11
      DNS2: 1.1.1.1
    restart: ${RESTART_MODE}
    networks:
        discovery:
            ipv4_address: 10.0.0.54
    depends_on:
      - traefik
    labels:
       # required when using --docker.exposedbydefault=false
       - "traefik.enable=true"
       # https://www.techjunktrunk.com/docker/2017/11/03/traefik-default-server-catch-all/
       - "traefik.frontend.rule=HostRegexp:pihole-shokohsc.duckdns.org,{catchall:.*}"
       - "traefik.frontend.priority=1"
       - "traefik.backend=pihole"
       - "traefik.port=80"

  grafana:
    container_name: grafana
    image: grafana/grafana
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    networks:
        discovery:
            ipv4_address: 10.0.0.55
    volumes:
      - ./config/grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana-shokohsc.duckdns.org
      GF_SECURITY_ADMIN_PASSWORD: ${GLOBAL_PASSWORD}
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/grafana"
      - "traefik.backend=grafana"
      - "traefik.port=3000"

  openvpn-as:
    container_name: openvpn-as
    image: linuxserver/openvpn-as
    domainname: ${DOMAIN_NAME}
    cap_add:
      - net_admin
    privileged: true
    restart: ${RESTART_MODE}
    ports:
      - "32767:1194/udp"
      - "32766:51413/tcp"
      - "32766:51413/udp"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
      INTERFACE: ${NIC_INTERFACE}
    volumes:
      - ./config/openvpn:/config
      - /dev/net:/dev/net
    networks:
        discovery:
            ipv4_address: 10.0.0.56
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/openvpn-as"
      - "traefik.backend=openvpn-as"
      - "traefik.port=943"

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    network_mode: "service:openvpn-as"
    volumes:
      - ./config/transmission:/config
      - ./download:/downloads
      - ./download:/watch
    dns:
      - 10.0.0.54
    depends_on:
      - openvpn-as
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/transmission"
      - "traefik.backend=transmission"
      - "traefik.port=9091"

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/sabnzbd:/config
      - ./download:/downloads
    network_mode: "service:openvpn-as"
    dns:
      - 10.0.0.54
    depends_on:
      - openvpn-as
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/sabnzbd"
      - "traefik.backend=sabnzbd"
      - "traefik.port=8080"

  plex:
    container_name: plex
    image: linuxserver/plex
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    ports:
      - "32400:32400/udp"
      - "32469:32469/tcp"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/plex:/config
      - /mnt/media/tvshows:/data/tvshows
      - /mnt/media/movies:/data/movies
      - ./work/transcode:/transcode
    networks:
        discovery:
            ipv4_address: 10.0.0.57
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/plex"
      - "traefik.backend=plex"
      - "traefik.port=32400"

  headphones:
    container_name: headphones
    image: linuxserver/headphones
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/headphones:/config
      - ./download:/downloads
      - /mnt/media/music:/music
    networks:
        discovery:
            ipv4_address: 10.0.0.58
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/headphones"
      - "traefik.backend=headphones"
      - "traefik.port=8181"

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      - ./config/lidarr:/config
      - ./download:/downloads
      - /mnt/media/music:/music
    networks:
        discovery:
            ipv4_address: 10.0.0.59
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/lidarr"
      - "traefik.backend=lidarr"
      - "traefik.port=8686"

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/jackett:/config
      - ./download:/downloads
    networks:
        discovery:
            ipv4_address: 10.0.0.60
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/jackett"
      - "traefik.backend=jackett"
      - "traefik.port=9117"

  sickrage:
    container_name: sickrage
    image: linuxserver/sickrage
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/sickrage:/config
      - ./download:/downloads
      - /mnt/media/tvshows:/tv
    networks:
        discovery:
            ipv4_address: 10.0.0.61
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/sickrage"
      - "traefik.backend=sickrage"
      - "traefik.port=8081"

  mylar:
    container_name: mylar
    image: linuxserver/mylar
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/mylar:/config
      - ./download:/downloads
      - /mnt/media/comics:/comics
    networks:
        discovery:
            ipv4_address: 10.0.0.62
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/mylar"
      - "traefik.backend=mylar"
      - "traefik.port=8090"

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/bazarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tvshows:/tv
    networks:
        discovery:
            ipv4_address: 10.0.0.63
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/bazarr"
      - "traefik.backend=bazarr"
      - "traefik.port=6767"

  gazee:
    container_name: gazee
    image: linuxserver/gazee
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/gazee:/config
      - /mnt/media/comics:/comics
      - ./config/mylar:/mylar
    networks:
        discovery:
            ipv4_address: 10.0.0.64
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/gazee"
      - "traefik.backend=gazee"
      - "traefik.port=4242"

  libresonic:
    container_name: libresonic
    image: linuxserver/libresonic
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/libresonic:/config
      - /mnt/media/music:/music
    networks:
        discovery:
            ipv4_address: 10.0.0.65
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/libresonic"
      - "traefik.backend=libresonic"
      - "traefik.port=4040"

  lychee:
    container_name: lychee
    image: linuxserver/lychee
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
    volumes:
      - ./config/lychee:/config
      - /mnt/media/photos:/pictures
    networks:
        discovery:
            ipv4_address: 10.0.0.66
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/lychee"
      - "traefik.backend=lychee"
      - "traefik.port=80"

  photoshow:
    container_name: photoshow
    image: linuxserver/photoshow
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/photoshow:/config
      - /mnt/media/photos:/Pictures:ro
      - /mnt/media/photos:/Thumbs
    networks:
        discovery:
            ipv4_address: 10.0.0.67
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/photoshow"
      - "traefik.backend=photoshow"
      - "traefik.port=80"

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/heimdall:/config
    networks:
        discovery:
            ipv4_address: 10.0.0.68
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/heimdall"
      - "traefik.backend=heimdall"
      - "traefik.port=80"

  pydio:
    container_name: pydio
    image: linuxserver/pydio
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
    volumes:
      - ./config/pydio:/config
      - /mnt/media/data:/data
    networks:
        discovery:
            ipv4_address: 10.0.0.69
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/pydio"
      - "traefik.backend=pydio"
      - "traefik.port=443"

  portainer:
    container_name: portainer
    image: portainer/portainer
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer:/data
    networks:
        discovery:
            ipv4_address: 10.0.0.70
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/portainer"
      - "traefik.backend=portainer"
      - "traefik.port=9000"

  h5ai:
    container_name: h5ai
    image: clue/h5ai
    domainname: ${DOMAIN_NAME}
    restart: ${RESTART_MODE}
    volumes:
      - ./download:/var/www/downloads
      - ./work:/var/www/work
      - /mnt/games:/var/www/games
      - /mnt/media:/var/www/media
    networks:
        discovery:
            ipv4_address: 10.0.0.71
    dns:
      - 10.0.0.54
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:shokohsc.duckdns.org/h5ai"
      - "traefik.backend=h5ai"
      - "traefik.port=80"

networks:
  discovery:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.0.0/24
