version: '2'

networks:

    connected:
        driver: bridge
        ipam:
            driver: default
            config: # http://www.subnet-calculator.com/subnet.php?net_class=B
            - subnet: 172.16.0.0/25 # 172.16.0.1 - 172.16.0.126
              gateway: 172.16.0.126
              ip_range: 172.16.0.0/26 # 172.16.0.1 - 172.16.0.62

    hidden:
        internal: true

services:

    openvpn:
        container_name: openvpn
        image: kylemanna/openvpn
        cap_add:
            - net_admin
        restart: ${RESTART_MODE}
        ports:
            - "32767:1194/udp"
            - "32766:51413/tcp"
            - "32766:51413/udp"
            - "9001:9091"
        volumes:
            - ./config/openvpn:/etc/openvpn
        networks:
            - connected

    nginx: # Reverse proxy
        container_name: nginx
        image: nginx
        restart: ${RESTART_MODE}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./config/nginx/certs:/etc/nginx/certs
            - ./config/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ./config/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - connected

    duckdns: # Dynamic IP <-> Domain
        container_name: duckdns
        image: linuxserver/duckdns
        restart: ${RESTART_MODE}
        environment:
            SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
            TOKEN: ${PUID}
            TZ: ${TIMEZONE}
        networks:
            - connected

    transmission: # Torrent client
        container_name: transmission
        image: linuxserver/transmission
        restart: ${RESTART_MODE}
        volumes:
            - ./config/transmission:/config
            - ./download:/downloads
            - ./shared/transmission:/watch
        network_mode: "service:openvpn"
        depends_on:
            - openvpn

    plex: # Media server
        container_name: plex
        image: plexinc/pms-docker
        restart: ${RESTART_MODE}
        ports:
            - "9002:32400/tcp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        environment:
            ADVERTISE_IP: "http://${IP}:9002/"
            PLEX_CLAIM: ${PLEX_CLAIM}
            TZ: ${TIMEZONE}
        volumes:
            - ./config/plex:/config
            - ./download:/data
            - ./shared/plex:/data
            - ./work/plex:/transcode
        networks:
            - connected
        depends_on:
            - nginx
        hostname: plex

    gazee: # Comics connected server
        container_name: gazee
        image: linuxserver/gazee
        restart: ${RESTART_MODE}
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        volumes:
            - ./config/gazee:/config
            - ./download:/comics
            - ./shared/gazee:/comics
        ports:
            - "9003:4242"
        networks:
            - connected
        depends_on:
            - nginx

    lychee: # Picture tool connected server
        container_name: lychee
        image: linuxserver/lychee
        restart: ${RESTART_MODE}
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
        volumes:
            - ./config/lychee:/config
            - ./shared/lychee:/pictures
        ports:
            - "9004:80"
        networks:
            - connected
            - hidden
        depends_on:
            - nginx
            - mariadb

    pydio: # Online usb key connected server
        container_name: pydio
        image: linuxserver/pydio
        restart: ${RESTART_MODE}
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        volumes:
            - ./config/pydio:/config
            - ./config/nginx/certs/cert.pem:/config/keys/cert.crt:ro
            - ./config/nginx/certs/key.pem:/config/keys/cert.key:ro
            - ./work/pydio:/data
        ports:
            - "9005:443"
        networks:
            - connected
            - hidden
        depends_on:
            - nginx

    mariadb: # Database, pydio requirement
        container_name: mariadb
        image: mariadb
        restart: ${RESTART_MODE}
        environment:
            MYSQL_ROOT_PASSWORD: ${GLOBAL_PASSWORD}
        volumes:
            - ./config/mariadb:/var/lib/mysql
        networks:
            - hidden

    h5ai: # File exporer connected server
        container_name: h5ai
        image: clue/h5ai
        restart: ${RESTART_MODE}
        volumes:
            - ./download:/var/www/downloads
            - ./shared:/var/www/shared
        ports:
            - "9006:80"
        networks:
            - connected
        depends_on:
            - nginx

    # grafana: # Monitoring tool connected server
    #     container_name: grafana
    #     image: grafana/grafana
    #     restart: ${RESTART_MODE}
    #     environment:
    #         GF_SECURITY_ADMIN_PASSWORD: ${GLOBAL_PASSWORD}
    #         GF_SERVER_ROOT_URL: "http://${IP}/grafana"
    #     ports:
    #         - "9007:3000"
    #     networks:
    #         - connected
    #         - hidden
    #     depends_on:
    #         - nginx
    #         - influxdb
    #         - prometheus
    #
    # influxdb: # Database, grafana requirement
    #     container_name: influxdb
    #     image: influxdb
    #     restart: ${RESTART_MODE}
    #     networks:
    #         - hidden
    #
    # prometheus: # Database, grafana requirement
    #     container_name: prometheus
    #     image: prom/prometheus
    #     restart: ${RESTART_MODE}
    #     networks:
    #         - hidden

    samba: # SMB server read only guests
        container_name: samba
        image: dperson/samba
        command: '-s "shared;/mount;yes;yes;yes;all;none"'
        restart: ${RESTART_MODE}
        ports:
            - "139:139"
            - "445:445"
        volumes:
            - ./download:/mount/downloads
            - ./shared:/mount/shared
        networks:
            - hidden

    sftp: # Sftp server read/write users
        container_name: sftp
        image: atmoz/sftp
        command: 'shokohsc:${SFTP_PASSWORD}:1001'
        restart: ${RESTART_MODE}
        ports:
            - "32768:22"
        volumes:
            - ./download:/home/shokohsc/upload/downloads
            - ./shared:/home/shokohsc/upload/shared
        networks:
            - hidden

    adminer: # Admin mysql database tool web server
        container_name: adminer
        image: adminer
        restart: ${RESTART_MODE}
        ports:
            - "9008:8080"
        networks:
            - connected
            - hidden
        depends_on:
            - nginx
            - mariadb
