apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: autoheal
  name: autoheal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: autoheal
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: autoheal
    spec:
      containers:
      - env:
        - name: AUTOHEAL_INTERVAL
          value: "10"
        - name: AUTOHEAL_START_PERIOD
          value: "60"
        image: willfarrell/autoheal
        imagePullPolicy: ""
        name: autoheal
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: autoheal-hostpath0
      hostname: autoheal
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: autoheal-hostpath0
status: {}
