apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: comic-reader
  name: comic-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: comic-reader
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: comic-reader
    spec:
      containers:
      - image: shokohsc/server-comic-reader
        imagePullPolicy: ""
        name: comic-reader
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/www/symfony
          name: comic-reader-hostpath0
        - mountPath: /var/www/symfony/public/files/weekly
          name: comic-reader-hostpath1
        - mountPath: /var/www/symfony/public/files/all
          name: comic-reader-hostpath2
      hostname: comic-reader
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /src
        name: comic-reader-hostpath0
      - hostPath:
          path: /src/shared/gazee
        name: comic-reader-hostpath1
      - hostPath:
          path: /comics
        name: comic-reader-hostpath2
status: {}
