apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-diskover
  name: elasticsearch-diskover
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch-diskover
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: elasticsearch-diskover
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx512m -Xms512m
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
        imagePullPolicy: ""
        name: elasticsearch-diskover
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: src-elasticsearch-diskover-data
      hostname: elasticsearch-diskover
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /src
        name: src-elasticsearch-diskover-data
status: {}
