apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: warn
        image: 'docker.elastic.co/logstash/logstash:'
        imagePullPolicy: ""
        name: logstash
        ports:
        - containerPort: 5044
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-hostpath0
      hostname: logstash
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /src/config/logstash
        name: logstash-hostpath0
status: {}
