apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: mysqld-exporter
  name: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqld-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: mysqld-exporter
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_NAME
          value: root:@(mysql:3306)/
        image: prom/mysqld-exporter
        imagePullPolicy: ""
        name: mysqld-exporter
        resources: {}
      hostname: mysqld-exporter
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
