apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: transmission
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
        image: linuxserver/transmission
        imagePullPolicy: ""
        name: transmission
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: transmission-hostpath0
        - mountPath: /downloads
          name: transmission-hostpath1
        - mountPath: /watch
          name: transmission-hostpath2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /src/config/transmission
        name: transmission-hostpath0
      - hostPath:
          path: /src/download
        name: transmission-hostpath1
      - hostPath:
          path: /src/shared/transmission
        name: transmission-hostpath2
status: {}
