apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        - --cluster.listen-address=
        image: prom/alertmanager
        imagePullPolicy: ""
        name: alertmanager
        resources: {}
        volumeMounts:
        - mountPath: /etc/alertmanager/
          name: alertmanager-claim0
      hostname: alertmanager
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: alertmanager-claim0
        persistentVolumeClaim:
          claimName: alertmanager-claim0
status: {}
