apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
    traefik.docker.network: ""
    traefik.enable: "true"
    traefik.frontend.rule: Host:cadvisor.
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        traefik.docker.network: ""
        traefik.enable: "true"
        traefik.frontend.rule: Host:cadvisor.
        traefik.port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: gcr.io/google-containers/cadvisor
        imagePullPolicy: ""
        name: cadvisor
        resources: {}
        volumeMounts:
        - mountPath: /dev/disk
          name: cadvisor-claim0
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-claim1
          readOnly: true
        - mountPath: /sys
          name: cadvisor-claim2
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-claim3
          readOnly: true
        - mountPath: /rootfs
          name: cadvisor-claim4
          readOnly: true
      hostname: cadvisor
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cadvisor-claim0
        persistentVolumeClaim:
          claimName: cadvisor-claim0
          readOnly: true
      - name: cadvisor-claim1
        persistentVolumeClaim:
          claimName: cadvisor-claim1
          readOnly: true
      - name: cadvisor-claim2
        persistentVolumeClaim:
          claimName: cadvisor-claim2
          readOnly: true
      - name: cadvisor-claim3
        persistentVolumeClaim:
          claimName: cadvisor-claim3
          readOnly: true
      - name: cadvisor-claim4
        persistentVolumeClaim:
          claimName: cadvisor-claim4
          readOnly: true
status: {}
