apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo
        imagePullPolicy: ""
        name: mongo
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: src-mongo-data
      hostname: mongo
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: src-mongo-data
        persistentVolumeClaim:
          claimName: src-mongo-data
status: {}
