apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:portainer.
    traefik.port: "9000"
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:portainer.
        traefik.port: "9000"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: portainer
    spec:
      containers:
      - image: portainer/portainer
        imagePullPolicy: ""
        name: portainer
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: portainer-claim0
      hostname: portainer
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: portainer-claim0
        persistentVolumeClaim:
          claimName: portainer-claim0
status: {}
