apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.irc.frontend.rule: Host:irc.
    traefik.irc.port: "9000"
  creationTimestamp: null
  labels:
    io.kompose.service: thelounge
  name: thelounge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thelounge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.irc.frontend.rule: Host:irc.
        traefik.irc.port: "9000"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: thelounge
    spec:
      containers:
      - image: thelounge/thelounge
        imagePullPolicy: ""
        name: thelounge
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/thelounge
          name: src-thelounge-data
      hostname: thelounge
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: src-thelounge-data
        persistentVolumeClaim:
          claimName: src-thelounge-data
status: {}
