apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.docker.network: ""
    traefik.enable: "true"
    traefik.frontend.rule: Host:cadvisor.
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
        traefik.docker.network: ""
        traefik.enable: "true"
        traefik.frontend.rule: Host:cadvisor.
        traefik.port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: gcr.io/google-containers/cadvisor
        imagePullPolicy: ""
        name: cadvisor
        resources: {}
        volumeMounts:
        - mountPath: /dev/disk
          name: cadvisor-hostpath0
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-hostpath1
          readOnly: true
        - mountPath: /sys
          name: cadvisor-hostpath2
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-hostpath3
          readOnly: true
        - mountPath: /rootfs
          name: cadvisor-hostpath4
          readOnly: true
      hostname: cadvisor
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /dev/disk/
        name: cadvisor-hostpath0
      - hostPath:
          path: /var/lib/docker/
        name: cadvisor-hostpath1
      - hostPath:
          path: /sys
        name: cadvisor-hostpath2
      - hostPath:
          path: /var/run
        name: cadvisor-hostpath3
      - hostPath:
          path: /
        name: cadvisor-hostpath4
status: {}
