apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: duckdns
  name: duckdns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: duckdns
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: duckdns
    spec:
      containers:
      - env:
        - name: SUBDOMAINS
        - name: TOKEN
        - name: TZ
        image: linuxserver/duckdns
        imagePullPolicy: ""
        name: duckdns
        resources: {}
      hostname: duckdns
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
