apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: heartbeat
  name: heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heartbeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: heartbeat
    spec:
      containers:
      - args:
        - heartbeat
        - -e
        - -strict.perms=false
        image: 'docker.elastic.co/beats/heartbeat:'
        imagePullPolicy: ""
        name: heartbeat
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: heartbeat-claim0
          readOnly: true
        - mountPath: /usr/share/heartbeat/heartbeat.yml
          name: heartbeat-claim1
          readOnly: true
      hostname: heartbeat-sombra
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: heartbeat-claim0
        persistentVolumeClaim:
          claimName: heartbeat-claim0
          readOnly: true
      - name: heartbeat-claim1
        persistentVolumeClaim:
          claimName: heartbeat-claim1
          readOnly: true
status: {}
