apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_DB
          value: miflora
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_LOGGING_LEVEL
          value: warn
        - name: INFLUXDB_USER
          value: miflora
        - name: INFLUXDB_USER_PASSWORD
        image: influxdb
        imagePullPolicy: ""
        name: influxdb
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: src-influx-data
      hostname: influxdb
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: src-influx-data
        persistentVolumeClaim:
          claimName: src-influx-data
status: {}
