apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.docker.network: ""
    traefik.enable: "true"
    traefik.frontend.rule: Host:kibana.
    traefik.port: "5601"
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.docker.network: ""
        traefik.enable: "true"
        traefik.frontend.rule: Host:kibana.
        traefik.port: "5601"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: kibana
    spec:
      containers:
      - env:
        - name: LOGGING_QUIET
          value: "true"
        - name: SERVER_NAME
          value: kibana
        image: 'docker.elastic.co/kibana/kibana:'
        imagePullPolicy: ""
        name: kibana
        resources: {}
      hostname: kibana
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
