apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:monitor.
    traefik.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:monitor.
        traefik.port: "80"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: monitor
    spec:
      containers:
      - env:
        - name: OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT
        - name: OPENVPNMONITOR_DEFAULT_LATITUDE
        - name: OPENVPNMONITOR_DEFAULT_LONGITUDE
        - name: OPENVPNMONITOR_DEFAULT_MAPS
          value: "True"
        - name: OPENVPNMONITOR_DEFAULT_SITE
        - name: OPENVPNMONITOR_SITES_0_HOST
        - name: OPENVPNMONITOR_SITES_0_NAME
        - name: OPENVPNMONITOR_SITES_0_PORT
        image: ruimarinho/openvpn-monitor
        imagePullPolicy: ""
        name: monitor
        resources: {}
      hostname: monitor
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
