apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:parsec.
    traefik.port: "80"
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-wol
  name: nginx-wol
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-wol
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:parsec.
        traefik.port: "80"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: nginx-wol
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
        image: shokohsc/alpine-nginx
        imagePullPolicy: ""
        name: nginx-wol
        resources: {}
      hostname: nginx-wol
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
