apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.21.0 (HEAD)
    traefik.docker.network: ""
    traefik.enable: "true"
    traefik.frontend.rule: Host:redis.
    traefik.port: "5001"
  creationTimestamp: null
  labels:
    io.kompose.service: redis-ui
  name: redis-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.21.0 (HEAD)
        traefik.docker.network: ""
        traefik.enable: "true"
        traefik.frontend.rule: Host:redis.
        traefik.port: "5001"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: redis-ui
    spec:
      containers:
      - image: marian/rebrow
        imagePullPolicy: ""
        name: redis-ui
        resources: {}
      hostname: redis-ui
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
