auditbeat.modules:
    - module: auditd
      audit_rules: |
        -w /etc/passwd -p wa -k identity
        -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

    - module: file_integrity
      paths:
        - /bin
        - /usr/bin
        - /sbin
        - /usr/sbin
        - /etc
    
processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    
    - decode_json_fields:
        fields: ["message"]
        target: "json"
        overwrite_keys: true

output.logstash:
    hosts: ["logstash:5044"]
        
logging.json: true
logging.metrics.enabled: false
logging.level: warning

setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
