filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

logging.json: true
logging.metrics.enabled: false
logging.level: warning

setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
