output.logstash:
    hosts: ["logstash:5044"]

processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    
    - decode_json_fields:
        fields: ["message"]
        target: "json"
        overwrite_keys: true
            
logging.json: true
logging.metrics.enabled: false
logging.level: warning

setup.dashboards.enabled: true
setup.dashboards.index: 'journalbeat-7.4.2-*'
setup.kibana.host: 'kibana:5601'
