output.logstash:
    hosts: ["logstash:5044"]
  
logging.json: true
logging.metrics.enabled: false
logging.level: warning

setup.dashboards.enabled: true
setup.dashboards.index: 'journalbeat-7.4.2-*'
setup.kibana.host: 'kibana:5601'
