packetbeat.interfaces.device: any

packetbeat.flows:
    timeout: 30s
    period: 10s

packetbeat.protocols.dns:
    ports: [53]
    include_authorities: true
    include_additionals: true

packetbeat.protocols.http:
    ports: [80]

processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

    - decode_json_fields:
        fields: ["message"]
        target: "json"
        overwrite_keys: true

output.logstash:
    hosts: ["localhost:5044"]
        
logging.json: true
logging.metrics.enabled: false
logging.level: warning

setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
