################################################################
# Global configuration
################################################################

# Enable debug mode
#
# Optional
# Default: false
#
# debug = true

# Log level
#
# Optional
# Default: "ERROR"
#
# logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/adminer.shokohsc.pem"
      keyFile = "/etc/traefik/certs/adminer.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/comics.shokohsc.pem"
      keyFile = "/etc/traefik/certs/comics.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/commander.shokohsc.pem"
      keyFile = "/etc/traefik/certs/commander.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/chronograf.shokohsc.pem"
      keyFile = "/etc/traefik/certs/chronograf.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/gekko.shokohsc.pem"
      keyFile = "/etc/traefik/certs/gekko.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/grafana.shokohsc.pem"
      keyFile = "/etc/traefik/certs/grafana.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/graphite.shokohsc.pem"
      keyFile = "/etc/traefik/certs/graphite.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/h5ai.shokohsc.pem"
      keyFile = "/etc/traefik/certs/h5ai.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/heimdall.shokohsc.pem"
      keyFile = "/etc/traefik/certs/heimdall.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/irc.shokohsc.pem"
      keyFile = "/etc/traefik/certs/irc.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/kibana.shokohsc.pem"
      keyFile = "/etc/traefik/certs/kibana.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/mattermost.shokohsc.pem"
      keyFile = "/etc/traefik/certs/mattermost.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/mongo.shokohsc.pem"
      keyFile = "/etc/traefik/certs/mongo.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/monitor.shokohsc.pem"
      keyFile = "/etc/traefik/certs/monitor.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/music.shokohsc.pem"
      keyFile = "/etc/traefik/certs/music.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/pihole.shokohsc.pem"
      keyFile = "/etc/traefik/certs/pihole.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/paint.shokohsc.pem"
      keyFile = "/etc/traefik/certs/paint.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/peerflix.shokohsc.pem"
      keyFile = "/etc/traefik/certs/peerflix.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/plex.shokohsc.pem"
      keyFile = "/etc/traefik/certs/plex.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/portainer.shokohsc.pem"
      keyFile = "/etc/traefik/certs/portainer.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/openvpn.shokohsc.pem"
      keyFile = "/etc/traefik/certs/openvpn.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/rabbitmq.shokohsc.pem"
      keyFile = "/etc/traefik/certs/rabbitmq.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/redis.shokohsc.pem"
      keyFile = "/etc/traefik/certs/redis.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/routeur.shokohsc.pem"
      keyFile = "/etc/traefik/certs/routeur.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/rss.shokohsc.pem"
      keyFile = "/etc/traefik/certs/rss.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/stackedit.shokohsc.pem"
      keyFile = "/etc/traefik/certs/stackedit.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/torrent.shokohsc.pem"
      keyFile = "/etc/traefik/certs/torrent.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/traefik.shokohsc.pem"
      keyFile = "/etc/traefik/certs/traefik.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/transmission.shokohsc.pem"
      keyFile = "/etc/traefik/certs/transmission.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/wekan.shokohsc.pem"
      keyFile = "/etc/traefik/certs/wekan.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/wol.shokohsc.pem"
      keyFile = "/etc/traefik/certs/wol.shokohsc-key.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/zenbot.shokohsc.pem"
      keyFile = "/etc/traefik/certs/zenbot.shokohsc-key.pem"

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
# [traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "log/traefik.log"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
#
# Optional
# Default: os.Stdout
#
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
#
# Optional
# Default: "common"
#
# format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  # dashboard = false

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://10.10.10.10:2375"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Optional
# Default: ""
#
domain = "shokohsc"

# Expose containers by default in traefik
#
# Optional
# Default: true
#
exposedByDefault = false

# If set to true invalid SSL certificates are accepted for backends.
# This disables detection of man-in-the-middle attacks so should only be used on secure backend networks.
#
# Optional
# Default: false
#
insecureSkipVerify = true

[file]
  watch = true

[backends]
  [backends.pihole]
    [backends.pihole.servers]
      [backends.pihole.servers.server0]
      url = "http://192.168.1.50"
      weight = 1
  [backends.routeur]
    [backends.routeur.servers]
      [backends.routeur.servers.server0]
      url = "http://192.168.1.1"
      weight = 1

[frontends]
  [frontends.pihole]
  entryPoints = ["http", "https"]
  backend = "pihole"
  passHostHeader = true
  [frontends.pihole.routes]
    [frontends.pihole.routes.route0]
      rule = "Host:pihole.shokohsc"
    [frontends.pihole.routes.route1]
      rule = "AddPrefix: /admin"
  [frontends.routeur]
  entryPoints = ["http", "https"]
  backend = "routeur"
  passHostHeader = true
  [frontends.routeur.routes]
    [frontends.routeur.routes.route0]
      rule = "Host:routeur.shokohsc"
