[[tls.certificates]]
certFile = "/etc/traefik/certs/comics.shokohsc.pem"
keyFile = "/etc/traefik/certs/comics.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/commander.shokohsc.pem"
keyFile = "/etc/traefik/certs/commander.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/chronograf.shokohsc.pem"
keyFile = "/etc/traefik/certs/chronograf.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/grafana.shokohsc.pem"
keyFile = "/etc/traefik/certs/grafana.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/heimdall.shokohsc.pem"
keyFile = "/etc/traefik/certs/heimdall.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/kibana.shokohsc.pem"
keyFile = "/etc/traefik/certs/kibana.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/monitor.shokohsc.pem"
keyFile = "/etc/traefik/certs/monitor.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/paint.shokohsc.pem"
keyFile = "/etc/traefik/certs/paint.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/plex.shokohsc.pem"
keyFile = "/etc/traefik/certs/plex.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/portainer.shokohsc.pem"
keyFile = "/etc/traefik/certs/portainer.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/traefik.shokohsc.pem"
keyFile = "/etc/traefik/certs/traefik.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/transmission.shokohsc.pem"
keyFile = "/etc/traefik/certs/transmission.shokohsc-key.pem"
[[tls.certificates]]
certFile = "/etc/traefik/certs/wol.shokohsc.pem"
keyFile = "/etc/traefik/certs/wol.shokohsc-key.pem"
