apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
    traefik.docker.network: ""
    traefik.enable: "true"
    traefik.frontend.rule: Host:chronograf.
    traefik.port: "8888"
  creationTimestamp: null
  labels:
    io.kompose.service: chronograf
  name: chronograf
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
        traefik.docker.network: ""
        traefik.enable: "true"
        traefik.frontend.rule: Host:chronograf.
        traefik.port: "8888"
      creationTimestamp: null
      labels:
        io.kompose.service: chronograf
    spec:
      containers:
      - args:
        - --influxdb-url=http://influxdb:8086
        image: chronograf
        name: chronograf
        resources: {}
      restartPolicy: Always
status: {}
