apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: duckdns
  name: duckdns
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.service: duckdns
    spec:
      containers:
      - env:
        - name: SUBDOMAINS
        - name: TOKEN
        - name: TZ
        image: linuxserver/duckdns
        name: duckdns
        resources: {}
      restartPolicy: Always
status: {}
