apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
      - args:
        - filebeat
        - -e
        - -strict.perms=false
        image: docker.elastic.co/beats/filebeat:7.3.2
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: filebeat-claim0
        - mountPath: /var/lib/docker
          name: filebeat-claim1
          readOnly: true
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-claim2
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: filebeat-claim0
        persistentVolumeClaim:
          claimName: filebeat-claim0
      - name: filebeat-claim1
        persistentVolumeClaim:
          claimName: filebeat-claim1
          readOnly: true
      - name: filebeat-claim2
        persistentVolumeClaim:
          claimName: filebeat-claim2
          readOnly: true
status: {}
