apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:jenkins.
    traefik.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:jenkins.
        traefik.port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: ""
        name: jenkins
        resources: {}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: src-jenkins-data
        - mountPath: /usr/bin/docker
          name: jenkins-hostpath1
      hostname: jenkins
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /src
        name: src-jenkins-data
      - hostPath:
          path: /usr/bin/docker
        name: jenkins-hostpath1
status: {}
