apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: minecraft
  name: minecraft
spec:
  ports:
  - name: "25565"
    port: 25565
    targetPort: 25565
  selector:
    io.kompose.service: minecraft
status:
  loadBalancer: {}
