apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeexporter
  name: nodeexporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: nodeexporter
    spec:
      containers:
      - args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
        image: prom/node-exporter:v0.16.0
        name: nodeexporter
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/proc
          name: nodeexporter-claim0
          readOnly: true
        - mountPath: /host/sys
          name: nodeexporter-claim1
          readOnly: true
        - mountPath: /rootfs
          name: nodeexporter-claim2
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nodeexporter-claim0
        persistentVolumeClaim:
          claimName: nodeexporter-claim0
          readOnly: true
      - name: nodeexporter-claim1
        persistentVolumeClaim:
          claimName: nodeexporter-claim1
          readOnly: true
      - name: nodeexporter-claim2
        persistentVolumeClaim:
          claimName: nodeexporter-claim2
          readOnly: true
status: {}
