apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:plex.
    traefik.port: "32400"
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  ports:
  - name: "32400"
    port: 32400
    targetPort: 32400
  - name: 32400-udp
    port: 32400
    protocol: UDP
    targetPort: 32400
  - name: "32469"
    port: 32469
    targetPort: 32469
  - name: 32469-udp
    port: 32469
    protocol: UDP
    targetPort: 32469
  - name: "5353"
    port: 5353
    protocol: UDP
    targetPort: 5353
  - name: "1900"
    port: 1900
    protocol: UDP
    targetPort: 1900
  selector:
    io.kompose.service: plex
status:
  loadBalancer: {}
