apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: filebeat
    spec:
      containers:
      - args:
        - filebeat
        - -e
        - -strict.perms=false
        image: 'docker.elastic.co/beats/filebeat:'
        imagePullPolicy: ""
        name: filebeat
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: filebeat-hostpath0
        - mountPath: /var/lib/docker
          name: filebeat-hostpath1
          readOnly: true
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-hostpath2
          readOnly: true
      hostname: filebeat-sombra
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: filebeat-hostpath0
      - hostPath:
          path: /var/lib/docker
        name: filebeat-hostpath1
      - hostPath:
          path: /src/config/filebeat/filebeat.yml
        name: filebeat-hostpath2
status: {}
