apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pushgateway
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pushgateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --volumes hostPath
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src_hidden: "true"
        io.kompose.service: pushgateway
    spec:
      containers:
      - image: prom/pushgateway
        imagePullPolicy: ""
        name: pushgateway
        resources: {}
      hostname: pushgateway
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
