apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:blackbox.
    traefik.port: "9115"
  creationTimestamp: null
  labels:
    io.kompose.service: blackbox
  name: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blackbox
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:blackbox.
        traefik.port: "9115"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: blackbox
    spec:
      containers:
      - image: prom/blackbox-exporter:master
        imagePullPolicy: ""
        name: blackbox
        resources: {}
      hostname: blackbox
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
