apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cloudtorrent
  name: cloudtorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudtorrent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: cloudtorrent
    spec:
      containers:
      - image: shokohsc/cloud-torrent
        imagePullPolicy: ""
        name: cloudtorrent
        resources: {}
        volumeMounts:
        - mountPath: /downloads
          name: cloudtorrent-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cloudtorrent-claim0
        persistentVolumeClaim:
          claimName: cloudtorrent-claim0
status: {}
