apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:commander.
    traefik.port: "8000"
  creationTimestamp: null
  labels:
    io.kompose.service: commander
  name: commander
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: commander
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:commander.
        traefik.port: "8000"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: commander
    spec:
      containers:
      - image: coderaiser/cloudcmd
        imagePullPolicy: ""
        name: commander
        resources: {}
        volumeMounts:
        - mountPath: /mnt/fs
          name: commander-claim0
        - mountPath: /root/downloads
          name: commander-claim1
        - mountPath: /root/shared
          name: commander-claim2
        - mountPath: /root/media/WD1To
          name: commander-claim3
        - mountPath: /root/media/WD2To
          name: commander-claim4
      hostname: commander
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: commander-claim0
        persistentVolumeClaim:
          claimName: commander-claim0
      - name: commander-claim1
        persistentVolumeClaim:
          claimName: commander-claim1
      - name: commander-claim2
        persistentVolumeClaim:
          claimName: commander-claim2
      - name: commander-claim3
        persistentVolumeClaim:
          claimName: commander-claim3
      - name: commander-claim4
        persistentVolumeClaim:
          claimName: commander-claim4
status: {}
