apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: deluge
  name: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: deluge
    spec:
      containers:
      - env:
        - name: DELUGE_LOGLEVEL
          value: error
        - name: PGID
        - name: PUID
        - name: TZ
        image: linuxserver/deluge
        imagePullPolicy: ""
        name: deluge
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: deluge-claim0
        - mountPath: /downloads
          name: deluge-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: deluge-claim0
        persistentVolumeClaim:
          claimName: deluge-claim0
      - name: deluge-claim1
        persistentVolumeClaim:
          claimName: deluge-claim1
status: {}
