apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: openvpn
  name: openvpn
spec:
  ports:
  - name: "32767"
    port: 32767
    protocol: UDP
    targetPort: 1194
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: openvpn
status:
  loadBalancer: {}
