apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: sftp
  name: sftp
spec:
  ports:
  - name: "32768"
    port: 32768
    targetPort: 22
  selector:
    io.kompose.service: sftp
status:
  loadBalancer: {}
