apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "true"
    traefik.frontend.rule: Host:theia.
    traefik.port: "3000"
  creationTimestamp: null
  labels:
    io.kompose.service: theia
  name: theia
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: theia
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "true"
        traefik.frontend.rule: Host:theia.
        traefik.port: "3000"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.service: theia
    spec:
      containers:
      - image: theiaide/theia
        imagePullPolicy: ""
        name: theia
        resources: {}
      hostname: theia
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
