apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autoheal: "true"
    kompose.cmd: kompose convert --chart
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        autoheal: "true"
        kompose.cmd: kompose convert --chart
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: transmission
    spec:
      containers:
      - env:
        - name: PGID
        - name: PUID
        - name: TZ
        image: linuxserver/transmission
        imagePullPolicy: ""
        name: transmission
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: transmission-claim0
        - mountPath: /downloads
          name: transmission-claim1
        - mountPath: /watch
          name: transmission-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: transmission-claim0
        persistentVolumeClaim:
          claimName: transmission-claim0
      - name: transmission-claim1
        persistentVolumeClaim:
          claimName: transmission-claim1
      - name: transmission-claim2
        persistentVolumeClaim:
          claimName: transmission-claim2
status: {}
